from __future__ import annotations

PERMISSION_CATALOG: tuple[tuple[str, str, str], ...] = (
    ("dds.read", "dds", "Просмотр ДДС"),
    ("dds.classify", "dds", "Классификация операций ДДС"),
    ("dds.write", "dds", "Редактирование ДДС"),
    ("dds.rules.write", "dds", "Управление правилами классификации"),
    ("payroll.read", "payroll", "Просмотр зарплаты"),
    ("payroll.runs.write", "payroll", "Расчёт зарплаты"),
    ("payroll.runs.finalize", "payroll", "Финализация расчёта зарплаты"),
    ("payroll.adjustments.write", "payroll", "Корректировки зарплаты"),
    ("schedule.read", "schedule", "Просмотр графика смен"),
    ("schedule.write", "schedule", "Редактирование графика смен"),
    ("shifts.read", "shifts", "Просмотр учёта смен и выручки"),
    ("shifts.write", "shifts", "Ввод учёта смен и выручки"),
    ("inventory.read", "inventory", "Просмотр инвентаризаций"),
    ("inventory.write", "inventory", "Редактирование инвентаризаций"),
    ("inventory.audits.write", "inventory", "Проведение инвентаризаций"),
    ("staff.read", "staff", "Просмотр Штата"),
    ("staff.write", "staff", "Редактирование Штата"),
    ("staff.dismiss", "staff", "Увольнение сотрудников"),
    ("staff.reinstate", "staff", "Восстановление сотрудников"),
    ("couriers.read", "couriers", "Просмотр курьеров"),
    ("couriers.schedule.write", "couriers", "График курьеров"),
    ("couriers.assess.write", "couriers", "Оценки курьеров"),
    ("couriers.deposits.write", "couriers", "Депозиты курьеров"),
    ("deposits.read", "deposits", "Просмотр депозитов"),
    ("deposits.write", "deposits", "Редактирование депозитов"),
    ("vacations.read", "vacations", "Просмотр отпусков"),
    ("vacations.write", "vacations", "Редактирование отпусков"),
    ("accumulation_fund.read", "accumulation_fund", "Просмотр фонда накопления"),
    ("accumulation_fund.write", "accumulation_fund", "Редактирование фонда накопления"),
    ("settings.read", "settings", "Просмотр настроек"),
    ("settings.write", "settings", "Редактирование настроек"),
    ("access_control.users.write", "access_control", "Управление пользователями"),
    ("access_control.roles.write", "access_control", "Управление правами должностей"),
)

ALL_PERMISSION_CODES = frozenset(code for code, _module, _description in PERMISSION_CATALOG)
