#!/usr/bin/env bash
set -euo pipefail

caller_dir="$PWD"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

env_arg="${1:-.env.prod}"
if [[ "$env_arg" = /* ]]; then
  env_file="$env_arg"
elif (($# > 0)); then
  env_file="$caller_dir/$env_arg"
else
  env_file="$script_dir/.env.prod"
fi

cd "$script_dir"

if [[ -e "$env_file" ]]; then
  echo "Refusing to overwrite existing $env_file" >&2
  exit 1
fi

domain="${TEPLO_DOMAIN:-}"
admin_email="${TEPLO_ADMIN_EMAIL:-admin@teplo.local}"

if [[ -z "$domain" ]]; then
  read -r -p "TEPLO_DOMAIN: " domain
fi

if [[ -z "$domain" || "$domain" == "app.example.com" ]]; then
  echo "TEPLO_DOMAIN must be a real production domain" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate production secrets" >&2
  exit 1
fi

random_hex() {
  local bytes="$1"
  openssl rand -hex "$bytes"
}

umask 077
mkdir -p secrets/sber
chmod 700 secrets secrets/sber

cat >"$env_file" <<EOF
# Generated by deploy/init-prod-env.sh.
# Keep this file on the production host only. Do NOT commit it.

TEPLO_DOMAIN=$domain

ENVIRONMENT=production
AUTH_COOKIE_SECURE=true

POSTGRES_DB=teplo
POSTGRES_USER=teplo
POSTGRES_PASSWORD=$(random_hex 32)

TEPLO_ADMIN_EMAIL=$admin_email
TEPLO_ADMIN_PASSWORD=$(random_hex 24)

JWT_SECRET_KEY=$(random_hex 64)
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
JWT_REFRESH_TOKEN_EXPIRE_DAYS=90

BACKEND_CORS_ORIGINS=[]

TEPLO_BANK_CLIENT_MODE=live
SBER_API_ACCOUNT_NUMBER=
SBER_API_CA_BUNDLE_PATH=
TBANK_API_ACCOUNT_NUMBER=
EOF

chmod 600 "$env_file"

echo "Created $env_file with mode 600."
echo "Created secrets/sber for Sber mTLS files; mount path inside containers is /run/secrets/teplo/sber."
echo "Next: fill bank account numbers if needed, then run ./check-prod-secrets.sh $env_file."
