#!/usr/bin/env bash
set -euo pipefail

caller_dir="$PWD"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

env_arg="${1:-.env.prod}"
if [[ "$env_arg" = /* ]]; then
  env_file="$env_arg"
elif (($# > 0)); then
  env_file="$caller_dir/$env_arg"
else
  env_file="$script_dir/.env.prod"
fi

cd "$script_dir"

if [[ -e "$env_file" ]]; then
  echo "Refusing to overwrite existing $env_file" >&2
  exit 1
fi
integrations_env_file="$script_dir/.env.integrations"

domain="${TEPLO_DOMAIN:-}"
admin_email="${TEPLO_ADMIN_EMAIL:-admin@teplo.local}"

if [[ -z "$domain" ]]; then
  read -r -p "TEPLO_DOMAIN: " domain
fi

if [[ -z "$domain" || "$domain" == "app.example.com" ]]; then
  echo "TEPLO_DOMAIN must be a real production domain" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate production secrets" >&2
  exit 1
fi

random_hex() {
  local bytes="$1"
  openssl rand -hex "$bytes"
}

umask 077
mkdir -p secrets/sber
chmod 700 secrets secrets/sber

cat >"$env_file" <<EOF
# Generated by deploy/init-prod-env.sh.
# Keep this file on the production host only. Do NOT commit it.

TEPLO_DOMAIN=$domain

ENVIRONMENT=production
AUTH_COOKIE_SECURE=true

POSTGRES_DB=teplo
POSTGRES_USER=teplo
POSTGRES_PASSWORD=$(random_hex 32)

TEPLO_ADMIN_EMAIL=$admin_email
TEPLO_ADMIN_PASSWORD=$(random_hex 24)

JWT_SECRET_KEY=$(random_hex 64)
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
JWT_REFRESH_TOKEN_EXPIRE_DAYS=90

# Наш shared secret для входящего вебхука «Статус платежа» T-Банка: банк присылает его
# в Authorization: Bearer. В production без него api и scheduler НЕ СТАРТУЮТ (валидация
# Settings падает на импорте). Генерируем сразу — значение надо сообщить банку при
# подключении вебхука (openapi@tbank.ru).
TBANK_WEBHOOK_TOKEN=$(random_hex 32)
# Необязательный CSV-белый список IP банка; пусто — проверка по IP отключена.
TBANK_WEBHOOK_ALLOWED_IPS=

BACKEND_CORS_ORIGINS=[]

TEPLO_BANK_CLIENT_MODE=live
# Каких провайдеров опрашивает планировщик. Sber добавляют строкой sber,tbank — и тогда
# check-prod-secrets.sh начинает требовать весь набор SBER_API_*.
BANK_SYNC_PROVIDERS=tbank

# Ниже — контуры, которые старт не роняют, а тихо выключаются. Значения внешние, генерировать
# их нечем: заполняются вручную, и пустое поле здесь означает «контур выключен осознанно».
# Что именно отключается — построчно расписано в env.prod.example.

# Claude: распознавание счетов, ИИ-разбор налоговых документов, переоценка ОС. Без ключа
# работает только детерминированный слой. С российского IP Anthropic отвечает 403 даже на
# верный ключ, поэтому нужен ещё адрес релея и его общий секрет (deploy/anthropic-relay-worker.js).
ANTHROPIC_API_KEY=
ANTHROPIC_BASE_URL=
ANTHROPIC_RELAY_SECRET=

# Почта: входящие счета («Страница на оплату») и налоговые документы бухгалтера. Пароль —
# внешний пароль приложения, не пароль от ящика. Без пары логин+пароль оба прохода молчат:
# планировщик не пишет в лог даже «не настроено».
MAILRU_EMAIL=
MAILRU_APP_PASSWORD=
MAILRU_WORKMAIL=
MAILRU_WORKMAIL_PASSWORD=
MAIL_POLL_ENABLED=true
TAX_DOCUMENT_POLL_ENABLED=true
# Отправители налоговых документов (через запятую). Пусто — дефолт методологии; менять нужно
# при смене бухгалтера, письма с других адресов отбрасываются молча.
TAX_DOCUMENT_SENDERS=askad02@mail.ru

# Телеграм-бот приёмки: арендодатели присылают квитанции в мессенджер, владелец пересылает их
# боту. Пустой токен — контур выключен. Белого списка чатов нет: документ принимается от любого,
# а отправитель записывается в строку приёмки и виден в столбце «от кого».
TELEGRAM_INTAKE_BOT_TOKEN=
TELEGRAM_INTAKE_ENABLED=true

# СБИС (Saby) ЭДО: зеркало входящих документов. Без пары ключей синк выходит сразу, а кнопка
# «Синхронизировать» отвечает 409.
SBIS_APP_CLIENT_ID=
SBIS_SECRET_KEY=
SBIS_SYNC_ENABLED=true
EOF

chmod 600 "$env_file"

if [[ ! -e "$integrations_env_file" ]]; then
  cp env.integrations.example "$integrations_env_file"
  chmod 600 "$integrations_env_file"
fi

echo "Created $env_file with mode 600."
echo "Created .env.integrations with mode 600."
echo "Created secrets/sber for Sber mTLS files; mount path inside containers is /run/secrets/teplo/sber."
echo "Next: fill integration tokens if needed, then run ./check-prod-secrets.sh $env_file."
